### ISSUE TITLE
保存時ファイル名のカスタマイズ機能

### ISSUE THREAD

**Issue by icesou** [Y-dash/twitter-download-original-image#1]
ツイッターの画像が保存できなくなっていたので助かりました
ツイ廃なので画像をめっちゃ保存するんですが、保存名に投稿者のtwitterIDや投稿時固有URLを含めることは可能ですか?検討していただけたら幸いです

**Comment by Y-dash** [comment]
ご提案ありがとうございます。「あれば便利だろう」と感じる機能であり、技術的には可能ではあるのですが、現在実装の予定はありません。理由は2つあります。

# ユーザーから追加で権限許諾を得る必要がある

本拡張機能は動作がシンプルなため、ユーザーから得る権限もシンプルで済んでいます。以下3つです。

1. コンテキストメニュー (右クリックメニュー) を扱う (chrome.contextMenus)
2. ファイルのダウンロード (chrome.downloads)
3. Twitter の画像置き場 (pbs.twimg.com) へのアクセス (host_permissions)

おっしゃるような機能を追加するには、画像が添付されていたツイートを解析しなければなりません。そのために追加で以下の権限の許諾を得る必要があります。

1. (Twitter 上での右クリックのみに対応する場合 : ) twitter.com へのアクセス
2. (他サイトに埋め込まれたツイートなどへの右クリックにも対応する場合 : ) 全サイトへのアクセス
3. 名前の付けかたの好みは人によって違うため、その命名規則の設定を保存するための権限 (chrome.storage)

「ユーザーから追加で権限を得なくてよい」と「新機能を追加できる」の2択をこれまで繰り返し検討しましたが、前者を優先したいほうに天秤が傾き続けています。

# Twitter の情勢が不安定

現在の Twitter はオーナーの気分次第であり、朝令暮改といった様相です。時間を割いて新規機能を追加したところで、明日には動作しなくなっているかもしれません。

いまのところ、積極的に新規機能を追加する予定はありません。基本方針は「Twitter が仕様変更して来ても既存機能は使い続けられるように極力維持する」です。機能を複雑にすればするほど仕様変更から大きな影響を受けやすくなるため、シンプルなままにしておきたいと考えています。

現在の不安定極まりない Twitter に対して正面から向き合うのはかなりチャレンジングな行動です。恐れ入りますがご理解いただけますと幸いです。

**Comment by icesou** [comment]
本アプリケーションの指針とともに丁寧に検討、回答して頂き、ありがとうございました。きまぐれなX君に合わせてメンテするのは大変かと存じますが、それをしていただけるだけで有り難いです
